"""Unit tests for `.ailineignore` loading and matching semantics."""

import os
import tempfile
import unittest

from ailine.snapshot.ignore import (
    AILINEIGNORE_FILENAME,
    DEFAULT_AILINEIGNORE_PATTERNS,
    is_ignored,
    load_ignore_spec,
    render_default_ailineignore,
)


def _write(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(contents)


class DefaultsCoverageTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo = self.tmp.name

    def test_default_spec_ignores_common_paths(self):
        spec = load_ignore_spec(self.repo)
        for rel_path in (
            ".git/HEAD",
            ".ailine/snapshots/x.json",
            "__pycache__/foo.pyc",
            "src/__pycache__/foo.pyc",
            ".cursor/rules/tmp.mdc",
            ".vscode/settings.json",
            ".idea/workspace.xml",
            "mlruns/0/meta.yaml",
            "wandb/run-1/files/log",
            "dist/wheel-1.0.0.whl",
            "build/lib/foo.py",
            ".ruff_cache/abc/x",
            ".mypy_cache/3.12/x.json",
            ".pytest_cache/v/cache/lastfailed",
            ".dvc/cache/01/abc",
            ".venv/lib/python3.12/site-packages/x.py",
        ):
            self.assertTrue(
                is_ignored(rel_path, spec), msg=f"expected ignored: {rel_path}"
            )

    def test_default_spec_keeps_normal_paths(self):
        spec = load_ignore_spec(self.repo)
        for rel_path in ("src/main.py", "data/raw/values.csv", "README.md"):
            self.assertFalse(
                is_ignored(rel_path, spec), msg=f"expected NOT ignored: {rel_path}"
            )


class UserPatternsTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo = self.tmp.name

    def test_user_patterns_extend_defaults(self):
        _write(
            os.path.join(self.repo, AILINEIGNORE_FILENAME),
            "secrets/\n*.pem\n",
        )
        spec = load_ignore_spec(self.repo)
        self.assertTrue(is_ignored("secrets/aws.txt", spec))
        self.assertTrue(is_ignored("keys/server.pem", spec))
        self.assertFalse(is_ignored("server.crt", spec))

    def test_negation_overrides_defaults(self):
        # Default ignores `dist/`. Negate a single file inside.
        _write(
            os.path.join(self.repo, AILINEIGNORE_FILENAME),
            "!dist/keep.txt\n",
        )
        spec = load_ignore_spec(self.repo)
        self.assertTrue(is_ignored("dist/build.whl", spec))
        self.assertFalse(is_ignored("dist/keep.txt", spec))

    def test_comments_and_blanks_are_ignored(self):
        _write(
            os.path.join(self.repo, AILINEIGNORE_FILENAME),
            "# header comment\n\n   # indented comment\nsecret/\n",
        )
        spec = load_ignore_spec(self.repo)
        self.assertTrue(is_ignored("secret/x", spec))
        self.assertFalse(is_ignored("comment/x", spec))


class DirectoryOnlySemanticsTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo = self.tmp.name

    def test_directory_only_default_matches_files_inside(self):
        spec = load_ignore_spec(self.repo)
        self.assertTrue(is_ignored("build/output.bin", spec))
        # NOTE: pathspec's gitwildmatch treats trailing-slash patterns as
        # directory-only at MATCH time only if the candidate has trailing
        # slash. Files literally named `build` are not ignored.
        self.assertFalse(is_ignored("build", spec))


class RenderDefaultsTests(unittest.TestCase):
    def test_render_contains_each_default_pattern(self):
        rendered = render_default_ailineignore()
        for pattern in DEFAULT_AILINEIGNORE_PATTERNS:
            self.assertIn(pattern, rendered, msg=pattern)
        # Header is present so users see the guidance.
        self.assertIn("Generated by `ailine init-workspace`", rendered)


if __name__ == "__main__":
    unittest.main()
