"""Init/reset commands for the workspace and the demo flow.

Two distinct lifecycles live under one module:

* ``init-workspace`` — primary path for the pip-install workflow. Writes a
  minimal ``.ailine.yml`` template if missing, creates state directories,
  prints next steps. Does **not** clone any repo.
* ``init-demo <repo_url>`` — the legacy tutorial flow that clones a sample
  repo into ``./repo`` and persists the URL in ``ailine_config.txt``.
* ``reset-demo`` — narrow counterpart of ``init-demo``. Removes ONLY the
  artifacts created by the demo flow.

For backward compatibility, ``init`` and ``cleanup`` remain as deprecated
aliases that print a deprecation warning and forward to the demo commands.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess

import click

from ailine.config import constants
from ailine.config.loader import init_state_dirs
from ailine.web.state import set_repo_url


WORKSPACE_TEMPLATE = """\
# Generated by `ailine init-workspace`. See docs/track-contract.md for the full schema.
project:
  version: 1
  mode: track

track:
  repo_root: auto
  mlflow:
    mode: inherit       # inherit | wrap | none
    set_env: false
  dvc:
    verify: "off"       # off | warn | strict
    verify_commands: []

snapshot:
  exclude_globs:
    - ".git/**"
    - ".dvc/cache/**"
    - ".venv/**"
    - "__pycache__/**"
    - "*.pyc"
    - "*.pyo"
    - ".pytest_cache/**"
    - ".mypy_cache/**"
    - "mlruns/**"
    - ".ailine/**"
  large_file_mb: 50
  large_file_mode: prompt
  dvc_pointer_patterns:
    - "*.dvc"

dvc:
  remote_name:
  require_hash_fields: true
  ignore_paths: []

environment:
  enabled: true
  packages:
    - mlflow
    - dvc

run_capture:
  enabled: true
"""


@click.command("init-workspace", help="Bootstrap a project for `ailine track --` (no clone).")
@click.option(
    "--force",
    is_flag=True,
    help="Overwrite an existing .ailine.yml if present.",
)
def init_workspace_command(force: bool):
    target = constants.POLICY_PATH
    if os.path.exists(target) and not force:
        click.echo(f"{target} already exists. Pass --force to overwrite.")
    else:
        with open(target, "w", encoding="utf-8") as f:
            f.write(WORKSPACE_TEMPLATE)
        click.echo(f"Wrote {target}.")

    init_state_dirs()
    click.echo(f"State directory: {constants.STATE_DIR}")
    click.echo("Next: run 'ailine doctor' to verify, then 'ailine track -- <command>'.")


@click.command("init-demo", help="Clone a sample repo into ./repo for the tutorial flow.")
@click.argument("repo_url")
def init_demo_command(repo_url: str):
    if os.path.exists(constants.REPO_DIR):
        raise click.UsageError(
            f"Directory {constants.REPO_DIR} already exists. Run 'ailine reset-demo' first."
        )
    subprocess.run(["git", "clone", repo_url, constants.REPO_DIR], check=True)
    with open(constants.CONFIG_PATH, "w") as f:
        f.write(repo_url)
    subprocess.run(["git", "fetch"], check=True, cwd=constants.REPO_DIR)
    set_repo_url(repo_url)
    logging.info(f"Initialized AIline demo with {repo_url} in {constants.REPO_DIR}")
    click.echo(f"Initialized AIline demo with {repo_url} in {constants.REPO_DIR}")


@click.command("reset-demo", help="Remove demo artifacts (./repo, DB, mlruns/, snapshots/).")
def reset_demo_command():
    items_to_remove = [
        constants.MLFLOW_STORAGE_DIR,
        constants.REPO_DIR,
        constants.DB_PATH,
        constants.CONFIG_PATH,
        constants.DEFAULT_STORAGE_DIR,
    ]
    for item in os.listdir("."):
        if item.startswith("temp_") and os.path.isdir(item):
            items_to_remove.append(item)

    for item in items_to_remove:
        if os.path.isdir(item):
            shutil.rmtree(item, ignore_errors=True)
            logging.info(f"Removed directory: {item}")
            click.echo(f"Removed directory: {item}")
        elif os.path.isfile(item):
            os.remove(item)
            logging.info(f"Removed file: {item}")
            click.echo(f"Removed file: {item}")

    set_repo_url(None)
    logging.info("reset-demo complete")
    click.echo("reset-demo complete. Run 'ailine init-demo <repo_url>' to start fresh.")


@click.command("init", help="(deprecated) alias for `init-demo`.")
@click.argument("repo_url")
@click.pass_context
def deprecated_init_command(ctx: click.Context, repo_url: str):
    click.echo(
        "warning: `ailine init` is deprecated; use `ailine init-demo` (legacy clone) "
        "or `ailine init-workspace` (pip-install workflow).",
        err=True,
    )
    ctx.invoke(init_demo_command, repo_url=repo_url)


@click.command("cleanup", help="(deprecated) alias for `reset-demo`.")
@click.pass_context
def deprecated_cleanup_command(ctx: click.Context):
    click.echo(
        "warning: `ailine cleanup` is deprecated; use `ailine reset-demo`.",
        err=True,
    )
    ctx.invoke(reset_demo_command)
