"""Init/reset commands for the workspace and the demo flow.

Two distinct lifecycles live under one module:

* ``init-workspace`` — primary path for the pip-install workflow. Writes a
  minimal ``.ailine.yml`` template if missing, creates state directories,
  prints next steps. Does **not** clone any repo.
* ``init-demo <repo_url>`` — the legacy tutorial flow that clones a sample
  repo into ``./repo`` and persists the URL in ``ailine_config.txt``.
* ``reset-demo`` — narrow counterpart of ``init-demo``. Removes ONLY the
  artifacts created by the demo flow.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess

import click

from ailine.config import constants
from ailine.config.loader import init_state_dirs
from ailine.snapshot.ignore import (
    AILINEIGNORE_FILENAME,
    render_default_ailineignore,
)
from ailine.web.state import set_repo_url


WORKSPACE_TEMPLATE = """\
# Generated by `ailine init-workspace`. See docs/track-contract.md for the full schema.
project:
  version: 1
  mode: track

track:
  repo_root: auto
  mlflow:
    mode: inherit              # inherit | wrap | none
    set_env: false
    inherit_name_sync: auto    # off | auto | force
    link_strategy: tag         # tag | prelink | none
    link_poll_seconds: 3.0
  dvc:
    verify: "off"       # off | warn | strict
    verify_commands: []

snapshot:
  # Where snapshot bundles + content-addressed objects are written. Relative
  # values are resolved against the repo root. Default (when omitted): the
  # value of AILINE_STORAGE_DIR or ./.ailine/snapshots.
  storage_dir: .ailine/snapshots
  # Snapshot ignore patterns live in .ailineignore (gitignore syntax) at the
  # repo root, not here. `ailine init-workspace` seeds it with sensible
  # defaults; see docs/track-contract.md.
  large_file_mb: 50
  large_file_mode: prompt
  dvc_pointer_patterns:
    - "*.dvc"

dvc:
  remote_name:
  require_hash_fields: true
  ignore_paths: []

environment:
  enabled: true
  packages:
    - mlflow
    - dvc

run_capture:
  enabled: true

cleanup:
  remove:
    with_mlflow: false   # default for `ailine remove`; CLI `--with-mlflow` overrides
"""


def _print_mlflow_env_summary() -> None:
    """Print the effective MLflow + storage runtime values with their source.

    Surfaces *what AIline will actually use* the moment a user finishes
    bootstrapping a project, so a wrong tracking URI does not silently make
    runs invisible. When the values come from a non-AIline source (defaults
    or ``MLFLOW_TRACKING_URI``), also print a copy-pasteable ``export``
    snippet that pins them into the user's shell.
    """
    summary = constants.resolve_mlflow_environment()
    click.echo("")
    click.echo("Resolved MLflow environment:")
    click.echo(
        f"  tracking URI: {summary['tracking_uri']}    "
        f"(source: {summary['tracking_uri_source']})"
    )
    click.echo(
        f"  UI base:      {summary['ui_base']}    "
        f"(source: {summary['ui_base_source']})"
    )
    click.echo(
        f"  storage dir:  {summary['storage_dir']}    "
        f"(source: {summary['storage_dir_source']})"
    )

    pinned_sources = {"AILINE_MLFLOW_URI", "AILINE_MLFLOW_UI_BASE"}
    needs_pin = (
        summary["tracking_uri_source"] not in pinned_sources
        or summary["ui_base_source"] not in pinned_sources
    )
    if needs_pin:
        click.echo("")
        click.echo("To pin these for future shells, add to your rc:")
        click.echo(f"  export AILINE_MLFLOW_URI={summary['tracking_uri']}")
        click.echo(f"  export AILINE_MLFLOW_UI_BASE={summary['ui_base']}")


def _write_default_ailineignore(target_path: str, *, force: bool) -> None:
    """Idempotently seed ``target_path`` with the default ``.ailineignore`` content.

    Creates the file when missing; preserves an existing one unless
    ``force=True``. Echoes one line so users see what happened.
    """
    if os.path.exists(target_path) and not force:
        click.echo(f"{target_path} already exists. Pass --force to overwrite.")
        return
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(render_default_ailineignore())
    click.echo(f"Wrote {target_path}.")


@click.command("init-workspace", help="Bootstrap a project for `ailine track --` (no clone).")
@click.option(
    "--force",
    is_flag=True,
    help="Overwrite an existing .ailine.yml or .ailineignore if present.",
)
def init_workspace_command(force: bool):
    target = constants.POLICY_PATH
    if os.path.exists(target) and not force:
        click.echo(f"{target} already exists. Pass --force to overwrite.")
    else:
        with open(target, "w", encoding="utf-8") as f:
            f.write(WORKSPACE_TEMPLATE)
        click.echo(f"Wrote {target}.")

    _write_default_ailineignore(
        os.path.join(os.getcwd(), AILINEIGNORE_FILENAME), force=force
    )

    init_state_dirs()
    click.echo(f"State directory: {constants.STATE_DIR}")
    _print_mlflow_env_summary()
    click.echo("")
    click.echo(
        "Next: run 'ailine doctor' to verify, then 'ailine track -- <command>'. "
        "Customize ignored paths in .ailineignore."
    )


@click.command("init-demo", help="Clone a sample repo into ./repo for the tutorial flow.")
@click.argument("repo_url")
def init_demo_command(repo_url: str):
    if os.path.exists(constants.REPO_DIR):
        raise click.UsageError(
            f"Directory {constants.REPO_DIR} already exists. Run 'ailine reset-demo' first."
        )
    subprocess.run(["git", "clone", repo_url, constants.REPO_DIR], check=True)
    init_state_dirs()
    with open(constants.CONFIG_PATH, "w") as f:
        f.write(repo_url)
    subprocess.run(["git", "fetch"], check=True, cwd=constants.REPO_DIR)
    _write_default_ailineignore(
        os.path.join(constants.REPO_DIR, AILINEIGNORE_FILENAME), force=False
    )
    set_repo_url(repo_url)
    logging.info(f"Initialized AIline demo with {repo_url} in {constants.REPO_DIR}")
    click.echo(f"Initialized AIline demo with {repo_url} in {constants.REPO_DIR}")


@click.command(
    "reset-demo",
    help="Remove demo artifacts (./repo, DB, mlruns/, .ailine/snapshots/).",
)
def reset_demo_command():
    items_to_remove = [
        constants.MLFLOW_STORAGE_DIR,
        constants.REPO_DIR,
        constants.DB_PATH,
        constants.CONFIG_PATH,
        constants.DEFAULT_STORAGE_DIR,
    ]
    for item in os.listdir("."):
        if item.startswith("temp_") and os.path.isdir(item):
            items_to_remove.append(item)

    for item in items_to_remove:
        if os.path.isdir(item):
            shutil.rmtree(item, ignore_errors=True)
            logging.info(f"Removed directory: {item}")
            click.echo(f"Removed directory: {item}")
        elif os.path.isfile(item):
            os.remove(item)
            logging.info(f"Removed file: {item}")
            click.echo(f"Removed file: {item}")

    set_repo_url(None)
    logging.info("reset-demo complete")
    click.echo("reset-demo complete. Run 'ailine init-demo <repo_url>' to start fresh.")
